name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: 1.11.3
        otp-version: 23.2
    - name: Cache Elixir dependencies and Dialyzer PLT files
      uses: actions/cache@v2
      id: mix-cache
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-elixir-cache-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.OS }}-elixir-cache-
    - name: Install Elixir Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Cache JS Dependencies
      uses: actions/cache@v2
      with:
        path: assets/node_modules
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Install JS Dependencies
      run: npm install --prefix assets
    - name: JS Deploy
      run: npm run deploy --prefix assets
    - name: Check
      run: mix check
